Peer Review
Lily-Lilian/medical-core-landing-page pull request #1
Opened 2022-09-30 18:21 UTC by Lily-Lilian

2022-10-03 08:57 UTC, sezeranoJchrisostome requested changes
Well done @Lily-Lilian, I left some comments for you and you can also use `CRTL + SHFT + F`  to format your HTML doc

2022-10-03 08:57 UTC, sezeranoJchrisostome commented on Index.html
> +        <div class="middle__sectiontitle">Welcome
you can use kababa case here

2022-10-03 08:57 UTC, sezeranoJchrisostome commented on Index.html
> +        <div class="middle__sectiondescr">A Great Place to Receive Care</div>
use kabab case here too and use descriptive name

2022-10-03 08:57 UTC, sezeranoJchrisostome commented on Index.html
> +    <img class="main__introimg" src="./images/thumb-concept.png" alt="" >
also here, use kabab case

2022-10-03 08:57 UTC, sezeranoJchrisostome commented on Index.html
> +            <img class="team__img" src="./images/user-cover-1.png" alt="">
always is good idea to add description to you alt artibute

2022-10-03 08:57 UTC, sezeranoJchrisostome commented on Index.html
> +        <nav class="nav">
since we have that tag in HTML it's better to use another descriptive name for it

2022-10-03 12:46 UTC, rithaven commented on Index.html
> +    <div class="team__title">Team</div>
Here the block is team-layout and it's elements must be team-layout__title, team-layout__(...).
 every element within this block must start by team-layout as it is a block name

2022-10-03 12:51 UTC, rithaven commented on Index.html
> +    <section class="middle__section">
Here, this element "middle__section" must inherit from "middle " block

2022-10-04 10:36 UTC, sezeranoJchrisostome approved these changes
LGTM

2022-10-04 14:38 UTC, rithaven approved these changes

2022-10-05 12:48 UTC, karemarsy commented on Index.html
> +                class="team__img"
`team__img` is positioned outside the Block (team).

2022-10-06 08:45 UTC, ritha-kankindi approved these changes

2022-10-07 11:21 UTC, karemarsy approved these changes

2022-10-07 16:59 UTC, merged